"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});
// import * as formula from 'formulajs';

var FINANCIAL_FUNCTIONS = {
    // ACCRINT: formula.ACCRINT,
    // ACCRINTM: formula.ACCRINTM,
    // AMORDEGRC: formula.AMORDEGRC,
    // AMORLINC: formula.AMORLINC,
    // COUPDAYBS: formula.COUPDAYBS,
    // COUPDAYS: formula.COUPDAYS,
    // COUPDAYSNC: formula.COUPDAYSNC,
    // COUPNCD: formula.COUPNCD,
    // COUPNUM: formula.COUPNUM,
    // COUPPCD: formula.COUPPCD,
    // CUMIPMT: formula.CUMIPMT,
    // FV: formula.FV,
    // PMT: formula.PMT,
    // CUMPRINC: formula.CUMPRINC,
    // DB: formula.DB,
    // DDB: formula.DDB,
    // DISC: formula.DISC,
    // DOLLARDE: formula.DOLLARDE,
    // DOLLARFR: formula.DOLLARFR,
    // DURATION: formula.DURATION,
    // EFFECT: formula.EFFECT,
    // FVSCHEDULE: formula.FVSCHEDULE,
    // INTRATE: formula.INTRATE,
    // IPMT: formula.IPMT,
    // IRR: formula.IRR,
    // ISPMT: formula.ISPMT,
    // MDURATION: formula.MDURATION,
    // MIRR: formula.MIRR,
    // NPV: formula.NPV,
    // NOMINAL: formula.NOMINAL,
    // NPER: formula.NPER,
    // ODDFPRICE: formula.ODDFPRICE,
    // ODDFYIELD: formula.ODDFYIELD,
    // ODDLPRICE: formula.ODDLPRICE,
    // ODDLYIELD: formula.ODDLYIELD,
    // PDURATION: formula.PDURATION,
    // PPMT: formula.PPMT,
    // PRICE: formula.PRICE,
    // PRICEDISC: formula.PRICEDISC,
    // PRICEMAT: formula.PRICEMAT,
    // PV: formula.PV,
    // RATE: formula.RATE,
    // RECEIVED: formula.RECEIVED,
    // RRI: formula.RRI,
    // SLN: formula.SLN,
    // SYD: formula.SYD,
    // TBILLEQ: formula.TBILLEQ,
    // TBILLPRICE: formula.TBILLPRICE,
    // TBILLYIELD: formula.TBILLYIELD,
    // VDB: formula.VDB,
    // XIRR: formula.XIRR,
    // XNPV: formula.XNPV,
    // YIELD: formula.YIELD,
    // YIELDDISC: formula.YIELDDISC,
    // YIELDMAT: formula.YIELDMAT,
};

exports.FINANCIAL_FUNCTIONS = FINANCIAL_FUNCTIONS;