// import * as formula from 'formulajs';

const ENGINEERING_FUNCTIONS = {
    // BESSELI: formula.BESSELI,
    // BESSELJ: formula.BESSELJ,
    // BESSELK: formula.BESSELK,
    // BESSELY: formula.BESSELY,
    // BIN2DEC: formula.BIN2DEC,
    // BIN2HEX: formula.BIN2HEX,
    // BIN2OCT: formula.BIN2OCT,
    // BITAND: formula.BITAND,
    // BITLSHIFT: formula.BITLSHIFT,
    // BITOR: formula.BITOR,
    // BITRSHIFT: formula.BITRSHIFT,
    // BITXOR: formula.BITXOR,
    // COMPLEX: formula.COMPLEX,
    // CONVERT: formula.CONVERT,
    // DEC2BIN: formula.DEC2BIN,
    // DEC2HEX: formula.DEC2HEX,
    // DEC2OCT: formula.DEC2OCT,
    // DELTA: formula.DELTA,
    // ERF: formula.ERF,
    // ERFC: formula.ERFC,
    // GESTEP: formula.GESTEP,
    // HEX2BIN: formula.HEX2BIN,
    // HEX2DEC: formula.HEX2DEC,
    // HEX2OCT: formula.HEX2OCT,
    // IMABS: formula.IMABS,
    // IMREAL: formula.IMREAL,
    // IMAGINARY: formula.IMAGINARY,
    // IMARGUMENT: formula.IMARGUMENT,
    // IMCONJUGATE: formula.IMCONJUGATE,
    // IMCOS: formula.IMCOS,
    // IMCOSH: formula.IMCOSH,
    // IMCOT: formula.IMCOT,
    // IMDIV: formula.IMDIV,
    // IMSIN: formula.IMSIN,
    // IMEXP: formula.IMEXP,
    // IMLN: formula.IMLN,
    // IMLOG10: formula.IMLOG10,
    // IMLOG2: formula.IMLOG2,
    // IMPOWER: formula.IMPOWER,
    // IMPRODUCT: formula.IMPRODUCT,
    // IMSEC: formula.IMSEC,
    // IMSECH: formula.IMSECH,
    // IMSINH: formula.IMSINH,
    // IMSQRT: formula.IMSQRT,
    // IMCSC: formula.IMCSC,
    // IMCSCH: formula.IMCSCH,
    // IMSUB: formula.IMSUB,
    // IMSUM: formula.IMSUM,
    // IMTAN: formula.IMTAN,
    // OCT2BIN: formula.OCT2BIN,
    // OCT2DEC: formula.OCT2DEC,
    // OCT2HEX: formula.OCT2HEX,
};

export {
    ENGINEERING_FUNCTIONS,
};
